--------------------------------------------------------
--  DDL for Table CAMP_INFO_TBL
--------------------------------------------------------

  CREATE TABLE "CAMPING"."CAMP_INFO_TBL" 
   (	"ID" NUMBER(10,0), 
	"CAMP_NAME" VARCHAR2(100 CHAR), 
	"CATE1" VARCHAR2(100 CHAR), 
	"CATE2" VARCHAR2(100 CHAR), 
	"CATE3" VARCHAR2(100 CHAR), 
	"SIDO_NAME" VARCHAR2(30 CHAR), 
	"SIGUGUN_NAME" VARCHAR2(30 CHAR), 
	"EUPMYUNDONG_NAME" VARCHAR2(30 CHAR), 
	"RY_NAME" VARCHAR2(30 CHAR), 
	"BUNJI_NAME" VARCHAR2(30 CHAR), 
	"ROAD_NAME" VARCHAR2(30 CHAR), 
	"BUILDING_NUM" VARCHAR2(30 CHAR), 
	"LATITUDE" NUMBER(8,4), 
	"LONGITUDE" NUMBER(8,4), 
	"ZIP" VARCHAR2(5 CHAR), 
	"ROAD_ADDRESS" VARCHAR2(300 CHAR), 
	"JIBUN_ADDRESS" VARCHAR2(300 CHAR), 
	"PHONE" VARCHAR2(20 CHAR), 
	"HOMEPAGE" VARCHAR2(300 CHAR), 
	"VENDOR" VARCHAR2(100 CHAR), 
	"WEEKDAY_OP_STATUS" VARCHAR2(20 CHAR), 
	"WEEKEND_OP_STATUS" VARCHAR2(20 CHAR), 
	"SPRING_OP_STATUS" VARCHAR2(20 CHAR), 
	"SUMMER_OP_STATUS" VARCHAR2(20 CHAR), 
	"FALL_OP_STATUS" VARCHAR2(20 CHAR), 
	"WINTER_OP_STATUS" VARCHAR2(20 CHAR), 
	"FACIL_ELECTRICITY" VARCHAR2(20 CHAR), 
	"FACIL_HOT_WATER" VARCHAR2(20 CHAR), 
	"FACIL_WIFI" VARCHAR2(20 CHAR), 
	"FACIL_CAMPFIRE" VARCHAR2(20 CHAR), 
	"FACIL_TRAIL" VARCHAR2(20 CHAR), 
	"FACIL_POOL" VARCHAR2(20 CHAR), 
	"FACIL_PLAYGROUND" VARCHAR2(20 CHAR), 
	"FACIL_MART" VARCHAR2(20 CHAR), 
	"FACIL_RESTROOM" VARCHAR2(4 CHAR), 
	"FACIL_SHOWERROOM" VARCHAR2(4 CHAR), 
	"FACIL_SINK" VARCHAR2(4 CHAR), 
	"FACIL_EXTINGUISHER" VARCHAR2(10 CHAR), 
	"SURR_FACIL_FISHING" VARCHAR2(30 CHAR), 
	"SURR_FACIL_TRAIL" VARCHAR2(30 CHAR), 
	"SURR_FACIL_BEACH" VARCHAR2(30 CHAR), 
	"SURR_FACIL_MARITIME_LEISURE" VARCHAR2(30 CHAR), 
	"SURR_FACIL_VALLEY" VARCHAR2(30 CHAR), 
	"SURR_FACIL_STREAM" VARCHAR2(30 CHAR), 
	"SURR_FACIL_POOL" VARCHAR2(30 CHAR), 
	"SURR_FACIL_YOUTH_EXPERIENCE" VARCHAR2(30 CHAR), 
	"SURR_FACIL_RURAL_EXPERIENCE" VARCHAR2(30 CHAR), 
	"SURR_FACIL_CHILDRENS_PLAY" VARCHAR2(30 CHAR), 
	"GLAM_BED" VARCHAR2(30 CHAR), 
	"GLAM_TV" VARCHAR2(30 CHAR), 
	"GLAM_FREEZER" VARCHAR2(30 CHAR), 
	"GLAM_INTERNET" VARCHAR2(30 CHAR), 
	"GLAM_RESTROOM" VARCHAR2(30 CHAR), 
	"GLAM_AIRCON" VARCHAR2(30 CHAR), 
	"GLAM_HEATER" VARCHAR2(30 CHAR), 
	"GLAM_COOKWARE" VARCHAR2(30 CHAR), 
	"FACIL_CHARACTERISTICS" VARCHAR2(1000 CHAR), 
	"FACIL_DETAIL" LONG, 
	"REG_DATE" CHAR(10 BYTE), 
	"LOCATION" NUMBER, 
	"BOX_PHOTO_IMAGES" VARCHAR2(4000 BYTE), 
	"CAMP_INTRO_IMAGES" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."ID" IS '아이디';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."CAMP_NAME" IS '시설명';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."CATE1" IS '카테고리1';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."CATE2" IS '카테고리2';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."CATE3" IS '카테고리3';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SIDO_NAME" IS '시도 명칭';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SIGUGUN_NAME" IS '시군구 명칭';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."EUPMYUNDONG_NAME" IS '법정읍면동명칭';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."RY_NAME" IS '리 명칭';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."BUNJI_NAME" IS '번지';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."ROAD_NAME" IS '도로명 이름';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."BUILDING_NUM" IS '건물 번호';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."LATITUDE" IS '위도';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."LONGITUDE" IS '경도';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."ZIP" IS '우편번호';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."ROAD_ADDRESS" IS '도로명주소';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."JIBUN_ADDRESS" IS '지번주소';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."HOMEPAGE" IS '홈페이지';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."VENDOR" IS '사업주체';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."WEEKDAY_OP_STATUS" IS '평일 운영 여부';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."WEEKEND_OP_STATUS" IS '주말 운영 여부';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SPRING_OP_STATUS" IS '봄 운영 여부';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SUMMER_OP_STATUS" IS '여름 운영 여부';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FALL_OP_STATUS" IS '가을 운영 여부';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."WINTER_OP_STATUS" IS '겨울 운영 여부';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_ELECTRICITY" IS '부대시설 전기';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_HOT_WATER" IS '부대시설 온수';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_WIFI" IS '부대시설 무선인터넷';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_CAMPFIRE" IS '부대시설 장작판매';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_TRAIL" IS '부대시설 산책로';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_POOL" IS '부대시설 물놀이장';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_PLAYGROUND" IS '부대시설 놀이터';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_MART" IS '부대시설 마트';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_RESTROOM" IS '부대시설 화장실 수';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_SHOWERROOM" IS '부대시설 샤워실 수';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_SINK" IS '부대시설 씽크대 수';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_EXTINGUISHER" IS '부대시설 소화기 수';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SURR_FACIL_FISHING" IS '주변 시설 낚시';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SURR_FACIL_TRAIL" IS '주변 시설 산책로';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SURR_FACIL_BEACH" IS '주변 시설 물놀이(해수욕)';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SURR_FACIL_MARITIME_LEISURE" IS '주변 시설 물놀이(수상레저)';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SURR_FACIL_VALLEY" IS '주변 시설 물놀이(계곡)';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SURR_FACIL_STREAM" IS '주변 시설 물놀이(강)';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SURR_FACIL_POOL" IS '주변 시설 물놀이(수영장)';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SURR_FACIL_YOUTH_EXPERIENCE" IS '주변 시설 청소년체험시설';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SURR_FACIL_RURAL_EXPERIENCE" IS '주변 시설 농어촌체험시설';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."SURR_FACIL_CHILDRENS_PLAY" IS '주변 시설 어린이놀이시설';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."GLAM_BED" IS '글램핑 침대';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."GLAM_TV" IS '글램핑 티비';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."GLAM_FREEZER" IS '글램핑 냉장고';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."GLAM_INTERNET" IS '글램핑 유무선인터넷';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."GLAM_RESTROOM" IS '글램핑 내부화장실';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."GLAM_AIRCON" IS '글램핑 에어컨';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."GLAM_HEATER" IS '글램핑 난방기구';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."GLAM_COOKWARE" IS '글램핑 취사도구';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_CHARACTERISTICS" IS '시설 특징';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."FACIL_DETAIL" IS '시설 소개';
   COMMENT ON COLUMN "CAMPING"."CAMP_INFO_TBL"."REG_DATE" IS '최종작성일';
